//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UotanToolbox.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UotanToolbox.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Current device does not support this command! 的本地化字符串。
        /// </summary>
        public static string Dialog_NotSupported {
            get {
                return ResourceManager.GetString("Dialog_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful! 的本地化字符串。
        /// </summary>
        public static string Dialog_Successful {
            get {
                return ResourceManager.GetString("Dialog_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device is not connected! 的本地化字符串。
        /// </summary>
        public static string Dialog_Unconnected {
            get {
                return ResourceManager.GetString("Dialog_Unconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device connection status error! 的本地化字符串。
        /// </summary>
        public static string Dialog_WrongStatus {
            get {
                return ResourceManager.GetString("Dialog_WrongStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ADB reboot to 的本地化字符串。
        /// </summary>
        public static string Home_AdbRebootTo {
            get {
                return ResourceManager.GetString("Home_AdbRebootTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Android SDK 的本地化字符串。
        /// </summary>
        public static string Home_AndroidSDK {
            get {
                return ResourceManager.GetString("Home_AndroidSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Home_BackButton {
            get {
                return ResourceManager.GetString("Home_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery 的本地化字符串。
        /// </summary>
        public static string Home_Battery {
            get {
                return ResourceManager.GetString("Home_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 9008 的本地化字符串。
        /// </summary>
        public static string Home_Boot9008 {
            get {
                return ResourceManager.GetString("Home_Boot9008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootloader 的本地化字符串。
        /// </summary>
        public static string Home_Bootloader {
            get {
                return ResourceManager.GetString("Home_Bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootloader 的本地化字符串。
        /// </summary>
        public static string Home_BootloaderLock {
            get {
                return ResourceManager.GetString("Home_BootloaderLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button Analog 的本地化字符串。
        /// </summary>
        public static string Home_ButtonAnalog {
            get {
                return ResourceManager.GetString("Home_ButtonAnalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Device 的本地化字符串。
        /// </summary>
        public static string Home_ChooseDevice {
            get {
                return ResourceManager.GetString("Home_ChooseDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Name 的本地化字符串。
        /// </summary>
        public static string Home_CodeName {
            get {
                return ResourceManager.GetString("Home_CodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiled Version 的本地化字符串。
        /// </summary>
        public static string Home_CompiledVersion {
            get {
                return ResourceManager.GetString("Home_CompiledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectionStatus 的本地化字符串。
        /// </summary>
        public static string Home_ConnectionStatus {
            get {
                return ResourceManager.GetString("Home_ConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Framework 的本地化字符串。
        /// </summary>
        public static string Home_CPUABI {
            get {
                return ResourceManager.GetString("Home_CPUABI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Code Name 的本地化字符串。
        /// </summary>
        public static string Home_CPUCode {
            get {
                return ResourceManager.GetString("Home_CPUCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brand 的本地化字符串。
        /// </summary>
        public static string Home_DeviceBrand {
            get {
                return ResourceManager.GetString("Home_DeviceBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Info 的本地化字符串。
        /// </summary>
        public static string Home_DeviceInfo {
            get {
                return ResourceManager.GetString("Home_DeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string Home_DeviceModel {
            get {
                return ResourceManager.GetString("Home_DeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DisplayDensity 的本地化字符串。
        /// </summary>
        public static string Home_DisplayDensity {
            get {
                return ResourceManager.GetString("Home_DisplayDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fastboot 的本地化字符串。
        /// </summary>
        public static string Home_Fastboot {
            get {
                return ResourceManager.GetString("Home_Fastboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fastbootd 的本地化字符串。
        /// </summary>
        public static string Home_Fastbootd {
            get {
                return ResourceManager.GetString("Home_Fastbootd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fastboot reboot to 的本地化字符串。
        /// </summary>
        public static string Home_FastbootRebootTo {
            get {
                return ResourceManager.GetString("Home_FastbootRebootTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetching ... 的本地化字符串。
        /// </summary>
        public static string Home_Fetching {
            get {
                return ResourceManager.GetString("Home_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash Type 的本地化字符串。
        /// </summary>
        public static string Home_FlashType {
            get {
                return ResourceManager.GetString("Home_FlashType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home_HomeButton {
            get {
                return ResourceManager.GetString("Home_HomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Sidebar_HomePage {
            get {
                return ResourceManager.GetString("Sidebar_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kernal Version 的本地化字符串。
        /// </summary>
        public static string Home_KernalVersion {
            get {
                return ResourceManager.GetString("Home_KernalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock 的本地化字符串。
        /// </summary>
        public static string Home_LockScreen {
            get {
                return ResourceManager.GetString("Home_LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MotherboardID 的本地化字符串。
        /// </summary>
        public static string Home_MotherboardID {
            get {
                return ResourceManager.GetString("Home_MotherboardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MultiTask 的本地化字符串。
        /// </summary>
        public static string Home_MultiTask {
            get {
                return ResourceManager.GetString("Home_MultiTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Platform 的本地化字符串。
        /// </summary>
        public static string Home_Platform {
            get {
                return ResourceManager.GetString("Home_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power On Time 的本地化字符串。
        /// </summary>
        public static string Home_PowerOnTime {
            get {
                return ResourceManager.GetString("Home_PowerOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recovery 的本地化字符串。
        /// </summary>
        public static string Home_Recovery {
            get {
                return ResourceManager.GetString("Home_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Home_Refresh {
            get {
                return ResourceManager.GetString("Home_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution 的本地化字符串。
        /// </summary>
        public static string Home_Resolution {
            get {
                return ResourceManager.GetString("Home_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snapshot 的本地化字符串。
        /// </summary>
        public static string Home_Screenshot {
            get {
                return ResourceManager.GetString("Home_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutdown 的本地化字符串。
        /// </summary>
        public static string Home_Shutdown {
            get {
                return ResourceManager.GetString("Home_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sideload 的本地化字符串。
        /// </summary>
        public static string Home_Sideload {
            get {
                return ResourceManager.GetString("Home_Sideload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storage &amp; Memory 的本地化字符串。
        /// </summary>
        public static string Home_StorageAndMemory {
            get {
                return ResourceManager.GetString("Home_StorageAndMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string Home_System {
            get {
                return ResourceManager.GetString("Home_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vab Stadus 的本地化字符串。
        /// </summary>
        public static string Home_VabStadus {
            get {
                return ResourceManager.GetString("Home_VabStadus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VNDK Version 的本地化字符串。
        /// </summary>
        public static string Home_VNDKVersion {
            get {
                return ResourceManager.GetString("Home_VNDKVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume - 的本地化字符串。
        /// </summary>
        public static string Home_VolumeDown {
            get {
                return ResourceManager.GetString("Home_VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute 的本地化字符串。
        /// </summary>
        public static string Home_VolumeMute {
            get {
                return ResourceManager.GetString("Home_VolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume + 的本地化字符串。
        /// </summary>
        public static string Home_VolumeUp {
            get {
                return ResourceManager.GetString("Home_VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A-Only device 的本地化字符串。
        /// </summary>
        public static string Info_AOnly {
            get {
                return ResourceManager.GetString("Info_AOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Slot 的本地化字符串。
        /// </summary>
        public static string Info_ASlot {
            get {
                return ResourceManager.GetString("Info_ASlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locked 的本地化字符串。
        /// </summary>
        public static string Info_BLstatusLocked {
            get {
                return ResourceManager.GetString("Info_BLstatusLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlocked 的本地化字符串。
        /// </summary>
        public static string Info_BLstatusUnlocked {
            get {
                return ResourceManager.GetString("Info_BLstatusUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B Slot 的本地化字符串。
        /// </summary>
        public static string Info_BSlot {
            get {
                return ResourceManager.GetString("Info_BSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D 的本地化字符串。
        /// </summary>
        public static string Info_Day {
            get {
                return ResourceManager.GetString("Info_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H 的本地化字符串。
        /// </summary>
        public static string Info_Hour {
            get {
                return ResourceManager.GetString("Info_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M 的本地化字符串。
        /// </summary>
        public static string Info_Minute {
            get {
                return ResourceManager.GetString("Info_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S 的本地化字符串。
        /// </summary>
        public static string Info_Second {
            get {
                return ResourceManager.GetString("Info_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unauthorized Device 的本地化字符串。
        /// </summary>
        public static string Info_UnauthorizedDevice {
            get {
                return ResourceManager.GetString("Info_UnauthorizedDevice", resourceCulture);
            }
        }
    }
}
